# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='内容')),
            ],
        ),
        migrations.CreateModel(
            name='Improvement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('subject', models.CharField(max_length=255, verbose_name='件名')),
                ('done_date', models.DateField(verbose_name='処置完了日')),
                ('boss_confirmation', models.DateField(verbose_name='上司確認')),
            ],
        ),
        migrations.AddField(
            model_name='hh',
            name='hh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hhat', to='cms.Improvement', verbose_name='改善'),
        ),
    ]
